### ISSUE TITLE
Wrong time zone decected

### ISSUE THREAD

**Issue by fenhl** [DJDavid98/SledgeHammerTime#2]
If I visit the page with the system timezone set to Europe/Berlin, that timezone is correctly displayed in the dropdown. However, with the system timezone set to Etc/UTC, the dropdown shows Africa/Abidjan instead. If I had to guess, I'd say this is because Africa/Abidjan is the first timezone alphabetically whose offset currently matches that of Etc/UTC.

**Comment by fenhl** [comment]
I have my main computer's timezone set to UTC because it simplified converting to different timezones. UTC is just one example though, I'm concerned that there are other pairs of timezones which will be confused for each other.

To get the system timezone, I would recommend [`Intl.DateTimeFormat().resolvedOptions().timeZone`](https://stackoverflow.com/a/34602679/667338) rather than relying on an external library. It's widely supported and reliably returns the correct timezone.

**Comment by DJDavid98** [comment]
My main reason for originally relying on moment.js' detection was that it has its own internal timezone database and if this method call you suggested results in a timezone it does not know about then everything will break. I'm opting for a compromise whereby I get the timezone provide by this API and ask if moment knows about it. If it does, it will be used, otherwise I have to fall back to moment's guessing approach. This has been deployed and should be ready for checking, please reopen if the issue persists.
